apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: use-entire-request-body
spec:
  params:
  - name: body
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: use-entire-request-body-
    spec:
      taskSpec:
        params:
        - name: body
        steps:
          - name: echo-body
            image: ubuntu
            script: |
              #! /bin/bash
              echo '$(inputs.params.body)' > /tmp/paylod.json
      params:
      - name: body
        value: $(params.body)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: use-entire-request-body
spec:
  params:
  - name: body
    value: $(body)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: use-entire-request-body
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: use-entire-request-body
      bindings:
        - name: use-entire-request-body
      template:
        name: use-entire-request-body
